In [6]:
#import pandas
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

pip install pandas

pip install numpy

pip install skitlearn

pip install tiledbsoma --only-binary=:all:

pip install PyTDC

In [7]:
#read the dataset
data = pd.read_csv(r'DDI_data.csv')

In [8]:
# Using a method to control the rows and columns truncation
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 150)

In [9]:
#checking the dataset
data.head(10)

  drug1_id drug2_id   drug1_name            drug2_name                     interaction_type
0  DB00006  DB00346  Bivalirudin             Alfuzosin                  serum concentration
1  DB00006  DB13783  Bivalirudin            Acemetacin         risk or severity of bleeding
2  DB00006  DB06605  Bivalirudin              Apixaban             anticoagulant activities
3  DB00006  DB06695  Bivalirudin  Dabigatran etexilate             anticoagulant activities
4  DB00006  DB09075  Bivalirudin              Edoxaban             anticoagulant activities
5  DB00006  DB06228  Bivalirudin           Rivaroxaban             anticoagulant activities
6  DB00006  DB00227  Bivalirudin            Lovastatin                  serum concentration
7  DB00006  DB09030  Bivalirudin             Vorapaxar  risk or severity of adverse effects
8  DB00006  DB00683  Bivalirudin             Midazolam                  serum concentration
9  DB00006  DB00641  Bivalirudin           Simvastatin                  serum concentration

In [10]:
#checking the columns of the dataset
list(data.columns)

['drug1_id', 'drug2_id', 'drug1_name', 'drug2_name', 'interaction_type']

In [11]:
# Display the number of instances and features
data.shape

(222696, 5)

In [12]:
#checking the datatypes
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222696 entries, 0 to 222695
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   drug1_id          222696 non-null  object
 1   drug2_id          222696 non-null  object
 2   drug1_name        222696 non-null  object
 3   drug2_name        222696 non-null  object
 4   interaction_type  222696 non-null  object
dtypes: object(5)
memory usage: 8.5+ MB

In [13]:
#describing data
data.describe()

       drug1_id drug2_id   drug1_name drug2_name                     interaction_type
count    222696   222696       222696     222696                               222696
unique     1751     1789         1751       1789                                  114
top     DB00176  DB11672  Fluvoxamine   Curcumin  risk or severity of adverse effects
freq        925      876          925        876                                62767

In [14]:
#checking null values
data.isnull().sum()

drug1_id            0
drug2_id            0
drug1_name          0
drug2_name          0
interaction_type    0
dtype: int64

In [15]:
#checking null value percentage
data.isna().sum()/len(data)*100

drug1_id            0.0
drug2_id            0.0
drug1_name          0.0
drug2_name          0.0
interaction_type    0.0
dtype: float64

In [16]:
null_columns = data.columns[data.isnull().any()]
print("Columns with null values:")
print(null_columns)

Columns with null values:
Index([], dtype='object')

In [17]:
#checking unique values
data['interaction_type'].unique()

array(['serum concentration', 'risk or severity of bleeding',
       'anticoagulant activities', 'risk or severity of adverse effects',
       'metabolism', 'therapeutic efficacy', 'QTc-prolonging activities',
       'cardiotoxic activities',
       'serum concentration of active metabolites', 'excretion',
       'hyperkalemic activities', 'nephrotoxic activities', 'absorption',
       'risk or severity of renal failure',
       'immunosuppressive activities', 'risk or severity of hyperkalemia',
       'excretion rate of higher serum level', 'hepatotoxic activities',
       'neuromuscular blocking activities', 'neurotoxic activities',
       'bradycardic activities',
       'atrioventricular blocking (AV block) activities',
       'hypoglycemic activities', 'risk or severity of myelosuppression',
       'hypercalcemic activities', 'arrhythmogenic activities',
       'photosensitizing activities',
       'risk or severity of QTc prolongation', 'serotonergic activities',
       'thrombogenic activities', 'antiplatelet activities',
       'risk or severity of myopathy and rhabdomyolysis',
       'myopathic rhabdomyolysis activities',
       'risk or severity of rhabdomyolysis, myoglobinuria, and elevated creatine kinase (CPK)',
       'risk or severity of rhabdomyolysis',
       'risk or severity of myopathy, rhabdomyolysis, and myoglobinuria',
       'risk or severity',
       'central nervous system depressant (CNS depressant) activities',
       'neuroexcitatory activities', 'sedative activities',
       'diagnostic agent', 'hyponatremic activities',
       'antihypertensive activities', 'hypotensive activities',
       'orthostatic hypotensive activities',
       'risk or severity of angioedema',
       'risk or severity of hypotension, nitritoid reactions, facial flushing, nausea, and vomiting',
       'risk or severity of hypotension',
       'hypotensive, nephrotoxic, and hyperkalemic activities',
       'risk of hypersensitivity reaction to',
       'risk or severity of anemia and severe leukopenia',
       'vasodilatory activities',
       'risk or severity of ventricular arrhythmias',
       'risk or severity of renal failure and hyperkalemia',
       'adverse neuromuscular activities', 'bioavailability',
       'hypokalemic activities', 'fluid retaining activities',
       'hypertensive activities',
       'hypotensive and central nervous system depressant (CNS depressant) activities',
       'central neurotoxic activities', 'anticholinergic activities',
       'risk or severity of hypertension',
       'risk or severity of convulsion',
       'risk or severity of serotonin syndrome', 'stimulatory activities',
       'tachycardic activities',
       'risk or severity of sedation and somnolence',
       'bronchoconstrictory activities',
       'risk or severity of congestive heart failure and hypotension',
       'vasoconstricting activities', 'bronchodilatory activities',
       'analgesic activities', 'constipating activities',
       'excretion rate', 'respiratory depressant activities',
       'risk or severity of QTc prolongation, torsade de pointes, hypokalemia, hypomagnesemia, and cardiac arrest',
       'antipsychotic activities', 'ulcerogenic activities',
       'hypertensive and vasoconstricting activities',
       'vasopressor activities', 'risk or severity of hypokalemia',
       'risk or severity of ototoxicity and nephrotoxicity',
       'diuretic activities', 'risk or severity of heart failure',
       'protein binding', 'risk or severity of edema formation',
       'risk or severity of fluid retention', 'hyperglycemic activities',
       'risk or severity of severe leukopenia',
       'risk or severity of hyponatremia', 'risk or severity of myopathy',
       'dermatologic adverse activities',
       'absorption of reduced serum concentration and potentially',
       'myelosuppressive activities',
       'risk or severity of hypotension and neuromuscular blockade',
       'risk or severity of sinus node depression',
       'risk or severity of generalized seizure and bradycardia',
       'hypocalcemic activities', 'thrombocytopenic activities',
       'neutropenic activities', 'risk or severity of bradycardia',
       'ototoxic activities',
       'risk or severity of QTc prolongation and torsade de pointes',
       'teratogenic activities',
       'risk or severity of renal failure and rhabdomyolysis',
       'risk or severity of pulmonary toxicity',
       'antineoplastic activities', 'hypotensive activities of at',
       'central nervous system depressant (CNS depressant) and hypertensive activities',
       'risk or severity of intraocular pressure',
       'serum concentration of sulfate',
       'risk or severity of generalized seizure',
       'risk or severity of sedation'], dtype=object)

In [18]:
# importing a Python package to visualise variables.
import plotly.express as px

In [ ]:
#checking anythings histogram
Grade_fig = px.histogram(data, x='NACCDAYS')
Grade_fig.show()

In [ ]:
# function to find outliers
def find_outliers_IQR(data):

  q1=data.quantile(0.25)

  q3=data.quantile(0.75)

  IQR=q3-q1

  outliers = data[((data < (q1 - 1.5 * IQR)) | (data > (q3 + 1.5 * IQR)))]

  return outliers

In [ ]:
# Finding outliers for anything
outliers = find_outliers_IQR(data['NACCDAYS'])

print("number of outliers: "+ str(len(outliers)))

outliers

In [ ]:
outlier_rows = data.index[data["NACCDAYS"] > 5000].tolist()
print(len(outlier_rows))
print(outlier_rows)

In [ ]:
# clipping values thtat are over 5000
data["NACCDAYS"] = data["NACCDAYS"].clip(upper=5000)

In [ ]:
# replacing string values with numerical values while making everything lowercase so no case sensitivity 
data['PACKET'] = data['PACKET'].map({'I': 1, 'F': 2, 'T': 3, 'IT': 4})

In [ ]:
#checking unique values 
data['EDUC'].unique()

In [ ]:

data['EDUC'] = data['EDUC'].replace(99, np.nan)
Mean_edu = data['EDUC'].mean()
data['EDUC'].fillna(Mean_edu, inplace=True)

In [ ]:
data.describe(include='float')

In [ ]:
data.describe(include='object')

In [ ]:
# Remove duplicate rows
data = data.drop_duplicates()

In [ ]:
# changing datatype float to int
data = data.astype({'FORMVER':"int", 'VISITMO':"int", 'VISITDAY':"int", 'VISITYR':"int", 'BIRTHMO':"int", 'BIRTHYR':"int", 'EDUC':"int", 'NACCDAYS':"int"})